---
# tasks file to unseal a single vault pod (included by main.yml)

- name: "Unsealing pod: {{ current_vault_pod_name }}"
  ansible.builtin.debug:
    msg: "Attempting to unseal pod {{ current_vault_pod_name }} using {{ vault_post_deploy_unseal_keys_threshold }} keys."

- name: Apply unseal keys to pod {{ current_vault_pod_name }}
  ansible.builtin.command: >
    oc exec -n {{ vault_namespace }} {{ current_vault_pod_name }} --
    sh -c "vault operator unseal -tls-skip-verify {{ item }}"
  loop: "{{ vault_unseal_keys[:(vault_post_deploy_unseal_keys_threshold | int)] }}" # Use only threshold number of keys
  register: unseal_command_output
  changed_when: "'Sealed: false' in unseal_command_output.stdout or unseal_command_output.rc == 0" # More robust change detection might be needed
  failed_when: false # Check status explicitly below
  # Add a small delay between unseal attempts if needed, though usually not necessary
  # delay: 1

- name: Check seal status of pod {{ current_vault_pod_name }} after unseal attempt
  ansible.builtin.command: >
    oc exec -n {{ vault_namespace }} {{ current_vault_pod_name }} --
    sh -c "vault status -format=json -tls-skip-verify"
  register: post_unseal_status_check
  changed_when: false
  failed_when: false

- name: Parse seal status for pod {{ current_vault_pod_name }}
  ansible.builtin.set_fact:
    pod_is_sealed: "{{ (post_unseal_status_check.stdout | from_json).sealed | default(true) if post_unseal_status_check.rc == 0 and post_unseal_status_check.stdout != '' else true }}"
  when: post_unseal_status_check is defined

- name: Display unseal status for pod {{ current_vault_pod_name }}
  ansible.builtin.debug:
    msg: "Pod {{ current_vault_pod_name }} - Sealed: {{ pod_is_sealed | default('Unknown') }}"

- name: Fail if pod {{ current_vault_pod_name }} is still sealed after unseal attempts
  ansible.builtin.fail:
    msg: "Failed to unseal pod {{ current_vault_pod_name }}. It remains sealed after applying {{ vault_post_deploy_unseal_keys_threshold }} keys."
  when: pod_is_sealed | bool
