---
# tasks file for vault_helm_deploy

- name: Ensure Helm chart repository is added
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: "{{ vault_helm_chart_repo }}"
    state: present
  tags:
    - helm
    - vault_deploy

- name: Generate Helm values file from template
  ansible.builtin.template:
    src: vault-helm-values.yaml.j2
    dest: "/tmp/vault-helm-values.yaml"
    mode: '0644'
  # Variables for the template are taken from defaults and playbook vars

- name: Deploy Vault using Helm chart
  kubernetes.core.helm:
    name: "{{ vault_helm_release_name }}"
    chart_ref: "{{ vault_helm_chart_name }}"
    release_namespace: "{{ vault_namespace }}"
    create_namespace: false # Namespace should be created by openshift_prereqs role
    values_files:
      - "/tmp/vault-helm-values.yaml"
    chart_version: "{{ vault_helm_chart_version }}"
    wait: true
    timeout: "10m0s"
    atomic: true
    state: present
  tags:
    - helm
    - vault_deploy

# - name: Remove temporary Vault Helm values file
#   ansible.builtin.file:
#     path: "/tmp/vault-helm-values.yaml"
#     state: absent
#   when: true # Always attempt to remove the fixed path file
