name: Deploy OpenShift on Azure

"on":
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'Cluster Name'
        required: true
        type: string
      region:
        description: 'Azure Region'
        required: true
        type: choice
        options:
          - eastus
          - eastus2
          - westus
          - westus2
          - westeurope
          - northeurope
          - southeastasia
          - japaneast
      node_count:
        description: 'Worker Node Count'
        required: true
        default: '3'
        type: string
      vm_size:
        description: 'Worker VM Size'
        required: true
        default: 'Standard_D4s_v3'
        type: choice
        options:
          - Standard_D2s_v3
          - Standard_D4s_v3
          - Standard_D8s_v3
          - Standard_D16s_v3
          - Standard_F4s_v2
          - Standard_F8s_v2
          - Standard_F16s_v2
      openshift_version:
        description: 'OpenShift Version'
        required: true
        default: '4.18.0'
        type: string
      base_domain:
        description: 'Base Domain'
        required: true
        type: string
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production

env:
  CLUSTER_NAME: ${{ github.event.inputs.cluster_name }}
  REGION: ${{ github.event.inputs.region }}
  NODE_COUNT: ${{ github.event.inputs.node_count }}
  VM_SIZE: ${{ github.event.inputs.vm_size }}
  OPENSHIFT_VERSION: ${{ github.event.inputs.openshift_version }}
  BASE_DOMAIN: ${{ github.event.inputs.base_domain }}
  ENVIRONMENT: ${{ github.event.inputs.environment }}

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"type":"serviceAccount","project_id":"${{ secrets.PROJECT_ID }}","private_key_id":"${{ secrets.PRIVATE_KEY_ID }}","private_key":"${{ secrets.PRIVATE_KEY }}","client_email":"${{ secrets.CLIENT_EMAIL }}","client_id":"${{ secrets.CLIENT_ID }}","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"${{ secrets.CLIENT_X509_CERT_URL }}"}'
      - name: Create OpenShift Cluster
        run: |
          az group create --name openshift-cluster --location "$REGION"
          az openshift create --resource-group openshift-cluster --name "$CLUSTER_NAME" --location "$REGION" --compute-machine-type "$VM_SIZE" --worker-count "$NODE_COUNT" --service-principal "${{ secrets.SERVICE_PRINCIPAL }}" --client-id "${{ secrets.CLIENT_ID }}" --cluster-version "$OPENSHIFT_VERSION" --base-domain "$BASE_DOMAIN" --environment "$ENVIRONMENT"